### ISSUE TITLE
Workspace Input Field Wrapping Issue

### ISSUE THREAD

**Issue by rooparsh** [Anmol92verma/SlackAndroidClone#3]
The text wrapping is not working properly on workspace input screen. Attaching a screen recording for reference.
<img src = "https://user-images.githubusercontent.com/7676782/154785591-71bf9ebf-bb85-4677-90b9-17956b02e8cb.gif" width = "200"/>

**Comment by oianmol** [comment]
Right! I’m aware of this. Does textfield or basic text field allow to wrap the width ? Not sure but will check, I’m gonna look into intrinsic width and see if that helps. Will keep you posted but it’s not a priority right now. Thanks!

**Comment by Anmol92verma** [comment]
https://stackoverflow.com/questions/67719981/resizeable-basictextfield-in-jetpack-compose

**Comment by oianmol** [comment]
<img src = "https://user-images.githubusercontent.com/4393101/154834491-f2f466b1-30e7-436d-8876-e1cafb792df5.gif" width = "200"/>

Resolved this @rooparsh
